### ISSUE TITLE
[HoN Game] Changing the Outcome Logic

### ISSUE THREAD

**Issue by jay-dhanwant-yral** [yral-dapp/ds-dags#2]
Moving away from majority driven outcome logic to one that incorporates signals associated with virality of the video such as likes, views, watch time, etc.

- Will prevent users from gaming the system and will increase NOTs chosen
- Will induce unpredictability in the game increasing gameplays and retention
- Help increase content consumption

![Image](https://github.com/user-attachments/assets/bf7d3774-2df8-4835-a670-f1abdad7c1a7)

Creating batch jobs for relevant metrics (2 Days )

- [x] #3
- [x] #4
- [ ] #5

Simulation (2 Days)

- [x] #6
- [ ] #7
- [ ] #8

Service to return HON for each video 

- [ ] #9

**Comment by jay-dhanwant** [comment]
- Batch Jobs to initialise and update HON metric for each video
- Service to return HON for reach video

**Comment by Natasha-GB** [comment]
v1: Compare with similar video and its hyper-parameters
v2: Random injection of videos into feed to get realistic data around the video

**Comment by harshitasrivastav28** [comment]
- Started working on it yesterday

**Comment by harshitasrivastav28** [comment]
- Simulation by this week will be done

**Comment by Natasha-GB** [comment]
- Setting up a threshold to decide HOT or NOT (to be discussed today)

**Comment by harshitasrivastav28** [comment]
- Working on simulation to be closed by EOD
- Report button instrumentation is missing

**Comment by harshitasrivastav28** [comment]
- There were handful amount of metrics which were skewing up.
- We have further analysed the outliers
- Simulation of HON game on new logic to see what all videos should have end up winning and what videos would have end up losing

**Comment by Natasha-GB** [comment]
- Need to figure out deployment
- Jay to share video ids working as per new logic for validation
- Approximating global comparison for now, will be better as we have more data
- 300 to 700 based on deviation is the number of videos we'll need for moving to the new logic

**Comment by harshitasrivastav28** [comment]
- How to schedule and integrate the new logic and check the response needs discussion
